### PR TITLE
279 fix proj4 decode

### LINKED ISSUE #279: Since adaguc-server 2.10.0: using autowms gridded interpolated observations fail
Adaguc-server is unable to use GSIE gridded interpolated observations since 2.10.0:

D:002:pid20: adagucserverEC/CAutoResource.cpp:232 CAutoResource]               2023-08-21T07:09:33Z OGC REQUEST Remote resource /data/adaguc-autowms/INTER_OPER_R___RD1NRT__L3__20230818T080000_20230819T080000_0002.nc
[D:003:pid20: adagucserverEC/CRequest.cpp:752 CRequest]                         2023-08-21T07:09:33Z WMS GETCAPABILITIES
[E:004:pid20: adagucserverEC/CImageWarper.cpp:334 CImageWarper]                 2023-08-21T07:09:33Z Invalid projection: from " +proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +no_defs +<>"

The attached NetCDF file INTER_OPER_R___RD1NRT__L3__20230818T080000_20230819T080000_0002.nc does not work with autowms.

  
[INTER_OPER_R___RD1NRT__L3__20230818T080000_20230819T080000_0002.zip](https://github.com/KNMI/adaguc-server/files/12393237/INTER_OPER_R___RD1NRT__L3__20230818T080000_20230819T080000_0002.zip)

### PR DESCRIPTION
**Pull request by maartenplieger**
Fixes  https://github.com/KNMI/adaguc-server/issues/279

### CODE REVIEW

File: adagucserverEC/CDataReader.cpp [hunk 1]
```diff
@@ -297,6 +297,10 @@ bool CDataReader::copyCRSFromADAGUCProjectionVariable(CDataSource *dataSource, c
   // }
   dataSource->nativeProj4.copy(proj4Attr->toString().c_str());
 
+  // Fixes issue https://github.com/KNMI/adaguc-server/issues/279
+  dataSource->nativeProj4.replaceSelf("\"", "");
```
Comment (maartenplieger) [inline adagucserverEC/CDataReader.cpp]: I have asked on the proj mailing list and they are saying that this might change in the future. It is best only to remove the first " and ending " when the string starts with a ".

**Review by lukas-phaf — APPROVED** [review]
