### PR TITLE
Fixed include style in combination with vectors

### LINKED ISSUE #582: BUG: IncludeStyle does not work in combination with wind vectors
This works:

```xml
<Style name="windbarbs_kts_barb" title="Wind barbs" abstract="Rendered with barbs"> -->
  <ShadeInterval min="0" max="7" label="0-7 (&lt;3 bft)" fillcolor="#FFFFB4" />
  <ShadeInterval min="7" max="11" label="7-11 (3 bft)" fillcolor="#FFFF00" />
  <ShadeInterval min="11" max="17" label="11-17 (4 bft)" fillcolor="#81FF00" />
  <ShadeInterval min="17" max="22" label="17-22 (5 bft)" fillcolor="#008D2C" />
  <ShadeInterval min="22" max="28" label="22-28 (6 bft)" fillcolor="#00FFFF" />
  <ShadeInterval min="28" max="34" label="28-34 (7 bft)" fillcolor="#74A3FF" />
  <ShadeInterval min="34" max="41" label="34-41 (8 bft)" fillcolor="#0000FF" />
  <ShadeInterval min="41" max="48" label="41-48 (9 bft)" fillcolor="#FF30FF" />
  <ShadeInterval min="48" max="56" label="48-56 (10 bft)" fillcolor="#FF8100" />
  <ShadeInterval min="56" max="64" label="56-64 (11 bft)" fillcolor="#FF0000" />
  <ShadeInterval min="64" max="74" label="64-74 (12 bft / sshws 1)" fillcolor="#FFFF00" />
  <ShadeInterval min="74" max="84" label="74-84 (sshws 1)" fillcolor="#C0C0C0" />
  <ShadeInterval min="84" max="100" label="84-100 (sshws 2)" fillcolor="#818181" />
  <ShadeInterval min="100" max="200" label="100-200 (sshws 3-5)" fillcolor="#3E3E3E" />

  <Vector min="0" max="100" vectorstyle="barb" linewidth="1.2" linecolor="#FFFFFF80" plotvalue="false" outlinewidth="3.0" outlinecolor="#000000" />
  <RenderSettings renderhint="discreteclasses" settings="auto" interpolationmethod="bilinear" /> 
  <DataPostProc algorithm="pointsfromgrid" select="speed_component,direction_component" a="50"/>
</Style>
 ```
And this does not, but should work:

```xml
 <Style name="windbarbs_kts_ShadeInterval">
  <ShadeInterval min="0" max="7" label="0-7 (&lt;3 bft)" fillcolor="#FFFFB4" />
  <ShadeInterval min="7" max="11" label="7-11 (3 bft)" fillcolor="#FFFF00" />
  <ShadeInterval min="11" max="17" label="11-17 (4 bft)" fillcolor="#81FF00" />
  <ShadeInterval min="17" max="22" label="17-22 (5 bft)" fillcolor="#008D2C" />
  <ShadeInterval min="22" max="28" label="22-28 (6 bft)" fillcolor="#00FFFF" />
  <ShadeInterval min="28" max="34" label="28-34 (7 bft)" fillcolor="#74A3FF" />
  <ShadeInterval min="34" max="41" label="34-41 (8 bft)" fillcolor="#0000FF" />
  <ShadeInterval min="41" max="48" label="41-48 (9 bft)" fillcolor="#FF30FF" />
  <ShadeInterval min="48" max="56" label="48-56 (10 bft)" fillcolor="#FF8100" />
  <ShadeInterval min="56" max="64" label="56-64 (11 bft)" fillcolor="#FF0000" />
  <ShadeInterval min="64" max="74" label="64-74 (12 bft / sshws 1)" fillcolor="#FFFF00" />
  <ShadeInterval min="74" max="84" label="74-84 (sshws 1)" fillcolor="#C0C0C0" />
  <ShadeInterval min="84" max="100" label="84-100 (sshws 2)" fillcolor="#818181" />
  <ShadeInterval min="100" max="200" label="100-200 (sshws 3-5)" fillcolor="#3E3E3E" />
</Style>


<Style name="windbarbs_kts_barb2" title="Wind barbs 2" abstract="Rendered with barbs"> -->
  <IncludeStyle name="windbarbs_kts_ShadeInterval"/>
  <Vector  min="0" max="100" vectorstyle="barb" linewidth="1.2" linecolor="#FFFFFF80" plotvalue="false" outlinewidth="3.0" outlinecolor="#000000" />
  <RenderSettings renderhint="discreteclasses" settings="auto" interpolationmethod="bilinear" />
  <DataPostProc algorithm="pointsfromgrid" select="speed_component,direction_component" a="50"/>
</Style>
 ```

### PR DESCRIPTION
**Pull request by maartenplieger**
Since 6.0.0 it is possible to include styles into each other. The styleConfig pointer can only point to one style. Therefore removed direct styleConfig link from CStyleConfiguration class. All info is now collected into dedicated properties.

See data/config/datasets/test.uwcw_ha43_dini_5p5km_10x8.xml (https://github.com/KNMI/adaguc-server/pull/583/files#diff-addca8be27235c8a76a0305bac7afeb619f323dadbad1bee18bc3de2c9457b7b )

Fixes https://github.com/KNMI/adaguc-server/issues/582 (WIK request)

### CODE REVIEW

File: adagucserverEC/CConvertADAGUCPoint.cpp [hunk 1]
```diff
@@ -795,12 +795,11 @@ int CConvertADAGUCPoint::convertADAGUCPointData(CDataSource *dataSource, int mod
     float discSize = 1;
     if (dataSource != NULL) {
       CStyleConfiguration *styleConfiguration = dataSource->getStyle();
-      if (styleConfiguration != NULL && styleConfiguration->styleConfig != NULL) {
-        if (styleConfiguration->styleConfig->Point.size() == 1) {
-
-          if (!styleConfiguration->styleConfig->Point[0]->attr.discradius.empty()) {
+      if (styleConfiguration != NULL) {
+        for (auto pointInterval : styleConfiguration->pointIntervals) {
```
Comment (ernstdevreede) [inline adagucserverEC/CConvertADAGUCPoint.cpp:805]: If there is more than 1 pointinterval this always selects the discsize of the last iinterval, I guess.
Is that what we want?

Comment (maartenplieger) [reply adagucserverEC/CConvertADAGUCPoint.cpp:805]: I did not want to change existing functionality except for the issue reported by Rutger. This part of the code allows for one point configuration, see https://github.com/KNMI/adaguc-server/blob/master/doc/configuration/Point.md#pointstyle-zoomablepoint

Wrote https://github.com/KNMI/adaguc-server/issues/586

Comment (maartenplieger) [reply adagucserverEC/CConvertADAGUCPoint.cpp:805]: And it uses now the last Point you configured, which is what you want I think.

**Review by mgrunbauer — APPROVED** [review]
